export const irregularVerbs = [
  {
    v1: 'arise',
    v2: 'arose',
    v3: 'arisen',
    mean: 'ortaya çıkmak, doğmak',
  },
  {
    v1: 'awake',
    v2: 'awoke',
    v3: 'awoken',
    mean: 'uyanmak, uyandırmak',
  },
  {
    v1: 'be',
    v2: 'was/were',
    v3: 'been',
    mean: 'olmak',
  },
  {
    v1: 'bear',
    v2: 'bore',
    v3: 'born/borne',
    mean: 'taşımak, aklında olmak',
  },
  {
    v1: 'beat',
    v2: 'beat',
    v3: 'beaten/beat',
    mean: 'vurmak, dövmek',
  },
  {
    v1: 'become',
    v2: 'became',
    v3: 'become',
    mean: 'olmak',
  },
  {
    v1: 'begin',
    v2: 'began',
    v3: 'begun',
    mean: 'başlamak, başlatmak',
  },
  {
    v1: 'bend',
    v2: 'bent',
    v3: 'bent',
    mean: 'eğmek, eğilmek, bükmek',
  },
  {
    v1: 'bet',
    v2: 'bet',
    v3: 'bet',
    mean: 'bahse girmek',
  },
  {
    v1: 'bind',
    v2: 'bound',
    v3: 'bound',
    mean: 'bağlamak, yarayı sarmak',
  },
  {
    v1: 'bite',
    v2: 'bit',
    v3: 'bitten/bit',
    mean: 'ısırmak, sokmak',
  },
  {
    v1: 'bleed',
    v2: 'bled',
    v3: 'bled',
    mean: 'kanamak, içi sızlamak',
  },
  {
    v1: 'blow',
    v2: 'blew',
    v3: 'blown',
    mean: 'esmek, üflemek',
  },
  {
    v1: 'break',
    v2: 'broke',
    v3: 'broken',
    mean: 'kırmak, kırılmak',
  },
  {
    v1: 'breed',
    v2: 'bred',
    v3: 'bred',
    mean: 'yavrulamak, neden olmak',
  },
  {
    v1: 'bring',
    v2: 'brought',
    v3: 'brought',
    mean: 'getirmek, neden olmak',
  },
  {
    v1: 'broadcast',
    v2: 'broadcast',
    v3: 'broadcast',
    mean: 'yayınlamak, yaymak',
  },
  {
    v1: 'build',
    v2: 'built',
    v3: 'built',
    mean: 'inşa etmek, geliştirmek',
  },
  {
    v1: 'burn',
    v2: 'burnt',
    v3: 'burnt',
    mean: 'yanmak, yakmak',
  },
  {
    v1: 'burst',
    v2: 'burst',
    v3: 'burst',
    mean: 'patlamak, patlatmak',
  },
  {
    v1: 'buy',
    v2: 'bought',
    v3: 'bought',
    mean: 'satın almak',
  },
  {
    v1: 'catch',
    v2: 'caught',
    v3: 'caught',
    mean: 'tutmak,yakalamak,yetişmek',
  },
  {
    v1: 'choose',
    v2: 'chose',
    v3: 'chosen',
    mean: 'seçmek, karar vermek',
  },
  {
    v1: 'cling',
    v2: 'clung',
    v3: 'clung',
    mean: 'yapışmak, sıkı sıkı tutmak',
  },
  {
    v1: 'come',
    v2: 'came',
    v3: 'come',
    mean: 'gelmek',
  },
  {
    v1: 'cost',
    v2: 'cost',
    v3: 'cost',
    mean: 'mal olmak, etmek',
  },
  {
    v1: 'cut',
    v2: 'cut',
    v3: 'cut',
    mean: 'kesmek, kısmak',
  },
  {
    v1: 'dig',
    v2: 'dug',
    v3: 'dug',
    mean: 'kazmak, meanak',
  },
  {
    v1: 'dive',
    v2: 'dove',
    v3: 'dived',
    mean: '(suya) dalmak',
  },
  {
    v1: 'do',
    v2: 'did',
    v3: 'done',
    mean: 'yapmak, etmek',
  },
  {
    v1: 'draw',
    v2: 'drew',
    v3: 'drawn',
    mean: 'resim çizmek, berabere bitirmek',
  },
  {
    v1: 'dream',
    v2: 'dreamt',
    v3: 'dreamt',
    mean: 'rüya görmek, düşlemek, hayal etmek',
  },
  {
    v1: 'drink',
    v2: 'drank',
    v3: 'drunk',
    mean: 'içmek',
  },
  {
    v1: 'drive',
    v2: 'drove',
    v3: 'driven',
    mean: 'taşıt sürmek, yürütmek',
  },
  {
    v1: 'dwell',
    v2: 'dwelt',
    v3: 'dwelt',
    mean: 'oturmak, ikamet etmek',
  },
  {
    v1: 'eat',
    v2: 'ate',
    v3: 'eaten',
    mean: 'yemek yemek',
  },
  {
    v1: 'fall',
    v2: 'fell',
    v3: 'fallen',
    mean: 'düşmek, azalmak, yenilmek',
  },
  {
    v1: 'feed',
    v2: 'fed',
    v3: 'fed',
    mean: 'beslemek',
  },
  {
    v1: 'feel',
    v2: 'felt',
    v3: 'felt',
    mean: 'hissetmek, duymak',
  },
  {
    v1: 'fight',
    v2: 'fought',
    v3: 'fought',
    mean: 'savaşmak, dövüşmek',
  },
  {
    v1: 'find',
    v2: 'found',
    v3: 'found',
    mean: 'bulmak',
  },
  {
    v1: 'fit',
    v2: 'fit',
    v3: 'fit',
    mean: '(giysi) uymak',
  },
  {
    v1: 'flee',
    v2: 'fled',
    v3: 'fled',
    mean: 'kaçmak',
  },
  {
    v1: 'fling',
    v2: 'flung',
    v3: 'flung',
    mean: 'fırlatıp atmak, savurmak',
  },
  {
    v1: 'fly',
    v2: 'flew',
    v3: 'flown',
    mean: 'uçmak, uçurmak',
  },
  {
    v1: 'forbid',
    v2: 'forbade',
    v3: 'forbidden',
    mean: 'yasaklamak',
  },
  {
    v1: 'forecast',
    v2: 'forecast',
    v3: 'forecast',
    mean: 'tahmin etmek',
  },
  {
    v1: 'foresee',
    v2: 'foresaw',
    v3: 'foreseen',
    mean: 'önceden görmek',
  },
  {
    v1: 'foretell',
    v2: 'foretold',
    v3: 'foretold',
    mean: 'önceden haber vermek',
  },
  {
    v1: 'forget',
    v2: 'forgot',
    v3: 'forgotten',
    mean: 'unutmak',
  },
  {
    v1: 'forgive',
    v2: 'forgave',
    v3: 'forgiven',
    mean: 'bağışlamak',
  },
  {
    v1: 'freeze',
    v2: 'froze',
    v3: 'frozen',
    mean: 'donmak, dondurmak',
  },
  {
    v1: 'overthrow',
    v2: 'overthrew',
    v3: 'overthrown',
    mean: '(hükümet) devirmek, yıkmak',
  },
  {
    v1: 'pay',
    v2: 'paid',
    v3: 'paid',
    mean: 'ödemek',
  },
  {
    v1: 'plead',
    v2: 'pled',
    v3: 'pled',
    mean: 'yalvarmak, dilemek',
  },
  {
    v1: 'prove',
    v2: 'proved',
    v3: 'proven',
    mean: 'kanıtlamak',
  },
  {
    v1: 'put',
    v2: 'put',
    v3: 'put',
    mean: 'koymak, yerleştirmek',
  },
  {
    v1: 'quit',
    v2: 'quit',
    v3: 'quit',
    mean: 'bırakıp gitmek',
  },
  {
    v1: 'read',
    v2: 'read',
    v3: 'read',
    mean: 'okumak',
  },
  {
    v1: 'rebuild',
    v2: 'rebuilt',
    v3: 'rebuilt',
    mean: 'yeniden inşa etmek',
  },
  {
    v1: 'redo',
    v2: 'redid',
    v3: 'redone',
    mean: 'yeniden yapmak',
  },
  {
    v1: 'remake',
    v2: 'remade',
    v3: 'remade',
    mean: 'yeniden yapmak',
  },
  {
    v1: 'repay',
    v2: 'repaid',
    v3: 'repaid',
    mean: '(para) geri vermek, ödemek',
  },
  {
    v1: 'resell',
    v2: 'resold',
    v3: 'resold',
    mean: 'tekrar satmak, satmak',
  },
  {
    v1: 'reset',
    v2: 'reset',
    v3: 'reset',
    mean: 'yeniden ayarlamak',
  },
  {
    v1: 'rethink',
    v2: 'rethought',
    v3: 'rethought',
    mean: 'tekrar düşünmek',
  },
  {
    v1: 'rewrite',
    v2: 'rewrote',
    v3: 'rewritten',
    mean: 'yeniden yazmak',
  },
  {
    v1: 'ride',
    v2: 'rode',
    v3: 'ridden',
    mean: 'binmek(at, bisiklet)',
  },
  {
    v1: 'ring',
    v2: 'rang',
    v3: 'rung',
    mean: '(zil vb) çalmak',
  },
  {
    v1: 'rise',
    v2: 'rose',
    v3: 'risen',
    mean: 'doğmak, yükselmek',
  },
  {
    v1: 'run',
    v2: 'ran',
    v3: 'run',
    mean: 'koşmak',
  },
  {
    v1: 'saw',
    v2: 'sawed',
    v3: 'sawn',
    mean: 'testereyle kesmek',
  },
  {
    v1: 'say',
    v2: 'said',
    v3: 'said',
    mean: 'demek, söylemek',
  },
  {
    v1: 'see',
    v2: 'saw',
    v3: 'seen',
    mean: 'görmek, kavramak',
  },
  {
    v1: 'seek',
    v2: 'sought',
    v3: 'sought',
    mean: 'aramak, araştırmak',
  },
  {
    v1: 'sell',
    v2: 'sold',
    v3: 'sold',
    mean: 'satmak',
  },
  {
    v1: 'send',
    v2: 'sent',
    v3: 'sent',
    mean: 'göndermek',
  },
  {
    v1: 'set',
    v2: 'set',
    v3: 'set',
    mean: 'hazırlamak, kurmak',
  },
  {
    v1: 'sew',
    v2: 'sewed',
    v3: 'sewn',
    mean: 'dikiş dikmek',
  },
  {
    v1: 'shake',
    v2: 'shook',
    v3: 'shaken',
    mean: 'sallamak, sallanmak',
  },
  {
    v1: 'shave',
    v2: 'shaved',
    v3: 'shaven',
    mean: 'tıraş olmak, tıraş etmek',
  },
  {
    v1: 'shed',
    v2: 'shed',
    v3: 'shed',
    mean: 'dökmek, saçmak, akıtmak',
  },
  {
    v1: 'shine',
    v2: 'shone',
    v3: 'shone',
    mean: 'parlamak',
  },
  {
    v1: 'shoot',
    v2: 'shot',
    v3: 'shot',
    mean: 'ateş etmek, vurmak',
  },
  {
    v1: 'show',
    v2: 'showed',
    v3: 'shown',
    mean: 'göstermek',
  },
  {
    v1: 'shrink',
    v2: 'shrank',
    v3: 'shrunk',
    mean: 'çekmek, büzülmek',
  },
  {
    v1: 'shut',
    v2: 'shut',
    v3: 'shut',
    mean: 'kapamak',
  },
  {
    v1: 'sing',
    v2: 'sang',
    v3: 'sung',
    mean: 'şarkı söylemek, ötmek',
  },
  {
    v1: 'sink',
    v2: 'sank',
    v3: 'sunk',
    mean: 'batmak, batırmak',
  },
  {
    v1: 'sit',
    v2: 'sat',
    v3: 'sat',
    mean: 'oturmak',
  },
  {
    v1: 'slay',
    v2: 'slew',
    v3: 'slain',
    mean: 'katletmek',
  },
  {
    v1: 'sleep',
    v2: 'slept',
    v3: 'slept',
    mean: 'uyumak',
  },
  {
    v1: 'slide',
    v2: 'slid',
    v3: 'slid',
    mean: 'kaymak, kaydırmak',
  },
  {
    v1: 'smell',
    v2: 'smelt',
    v3: 'smelt',
    mean: 'koklamak, kokmak',
  },
  {
    v1: 'sow',
    v2: 'sowed',
    v3: 'sown',
    mean: '(tohum) ekmek',
  },
  {
    v1: 'speak',
    v2: 'spoke',
    v3: 'spoken',
    mean: 'konuşmak',
  },
  {
    v1: 'spell',
    v2: 'spelt',
    v3: 'spelt',
    mean: 'harf harf söylemek',
  },
  {
    v1: 'spend',
    v2: 'spent',
    v3: 'spent',
    mean: 'harcamak, geçirmek',
  },
  {
    v1: 'spill',
    v2: 'spilt',
    v3: 'spilt',
    mean: 'dökmek, dökülmek, sızmak',
  },
  {
    v1: 'spin',
    v2: 'spun',
    v3: 'spun',
    mean: 'hızla dönmek',
  },
  {
    v1: 'get',
    v2: 'got',
    v3: 'got',
    mean: 'almak, elde etmek, varmak',
  },
  {
    v1: 'give',
    v2: 'gave',
    v3: 'given',
    mean: 'vermek',
  },
  {
    v1: 'go',
    v2: 'went',
    v3: 'gone',
    mean: 'gitmek',
  },
  {
    v1: 'grind',
    v2: 'ground',
    v3: 'ground',
    mean: 'öğütmek, bilemek',
  },
  {
    v1: 'grow',
    v2: 'grew',
    v3: 'grown',
    mean: '(bitki vb) yetişmek, yetiştirmek',
  },
  {
    v1: 'hang',
    v2: 'hung',
    v3: 'hung',
    mean: 'asmak, asılmak',
  },
  {
    v1: 'have',
    v2: 'had',
    v3: 'had',
    mean: 'sahip olmak, yemek içmek',
  },
  {
    v1: 'hear',
    v2: 'heard',
    v3: 'heard',
    mean: 'duymak, işitmek',
  },
  {
    v1: 'hide',
    v2: 'hid',
    v3: 'hidden',
    mean: 'saklamak, saklanmak',
  },
  {
    v1: 'hit',
    v2: 'hit',
    v3: 'hit',
    mean: 'vurmak, çarpmak',
  },
  {
    v1: 'hold',
    v2: 'held',
    v3: 'held',
    mean: 'tutmak,tutturmak',
  },
  {
    v1: 'hurt',
    v2: 'hurt',
    v3: 'hurt',
    mean: 'acıtmak, acımak',
  },
  {
    v1: 'input',
    v2: 'input',
    v3: 'input',
    mean: 'bilgisayara veri girmek',
  },
  {
    v1: 'keep',
    v2: 'kept',
    v3: 'kept',
    mean: 'saklamak, korumak',
  },
  {
    v1: 'kneel',
    v2: 'knelt',
    v3: 'knelt',
    mean: 'diz çökmek',
  },
  {
    v1: 'knit',
    v2: 'knit',
    v3: 'knit',
    mean: 'örmek',
  },
  {
    v1: 'know',
    v2: 'knew',
    v3: 'known',
    mean: 'bilmek, tanımak',
  },
  {
    v1: 'lay',
    v2: 'laid',
    v3: 'laid',
    mean: 'yaymak, sermek',
  },
  {
    v1: 'lead',
    v2: 'led',
    v3: 'led',
    mean: 'götürmek, rehberlik etmek',
  },
  {
    v1: 'lean',
    v2: 'leant',
    v3: 'leant',
    mean: 'yana yatmak, yaslanmak',
  },
  {
    v1: 'leap',
    v2: 'leapt',
    v3: 'leapt',
    mean: 'sıçramak, üstünden atlamak',
  },
  {
    v1: 'learn',
    v2: 'learnt',
    v3: 'learnt',
    mean: 'öğrenmek',
  },
  {
    v1: 'leave',
    v2: 'left',
    v3: 'left',
    mean: 'ayrılmak, bırakmak',
  },
  {
    v1: 'lend',
    v2: 'lent',
    v3: 'lent',
    mean: 'ödünç vermek',
  },
  {
    v1: 'let',
    v2: 'let',
    v3: 'let',
    mean: 'izin vermek, bırakmak',
  },
  {
    v1: 'lie',
    v2: 'lay',
    v3: 'lain',
    mean: 'uzanmak, yalan söylemek',
  },
  {
    v1: 'light',
    v2: 'lit',
    v3: 'lit',
    mean: 'yakmak, yanmak',
  },
  {
    v1: 'lose',
    v2: 'lost',
    v3: 'lost',
    mean: 'kaybetmek, yenilmek',
  },
  {
    v1: 'make',
    v2: 'made',
    v3: 'made',
    mean: 'yapmak, hazırlamak',
  },
  {
    v1: 'mean',
    v2: 'meant',
    v3: 'meant',
    mean: 'meanına gelmek',
  },
  {
    v1: 'meet',
    v2: 'met',
    v3: 'met',
    mean: 'karşılaşmak, tanışmak, karşılamak',
  },
  {
    v1: 'mishear',
    v2: 'misheard',
    v3: 'misheard',
    mean: 'yanlış duymak',
  },
  {
    v1: 'mislead',
    v2: 'misled',
    v3: 'misled',
    mean: 'saptırmak, yanıltmak',
  },
  {
    v1: 'misread',
    v2: 'misread',
    v3: 'misread',
    mean: 'yanlış okumak',
  },
  {
    v1: 'mistake',
    v2: 'mistook',
    v3: 'mistaken',
    mean: 'yanlış meanak, karıştırmak',
  },
  {
    v1: 'misunderstand',
    v2: 'misunderstood',
    v3: 'misunderstood',
    mean: 'yanlış meanak',
  },
  {
    v1: 'mow',
    v2: 'mowed',
    v3: 'mown',
    mean: 'biçmek',
  },
  {
    v1: 'outsell',
    v2: 'outsold',
    v3: 'outsold',
    mean: 'daha fazla satmak',
  },
  {
    v1: 'overcome',
    v2: 'overcame',
    v3: 'overcome',
    mean: 'üstesinden gelmek',
  },
  {
    v1: 'overdo',
    v2: 'overdid',
    v3: 'overdone',
    mean: 'abartmak',
  },
  {
    v1: 'overeat',
    v2: 'overate',
    v3: 'overeaten',
    mean: 'aşırı yemek',
  },
  {
    v1: 'overhear',
    v2: 'overheard',
    v3: 'overheard',
    mean: 'kulak misafiri olmak',
  },
  {
    v1: 'overpay',
    v2: 'overpaid',
    v3: 'overpaid',
    mean: 'fazla ödemek',
  },
  {
    v1: 'override',
    v2: 'overrode',
    v3: 'overridden',
    mean: 'umursamamak',
  },
  {
    v1: 'overrun',
    v2: 'overran',
    v3: 'overrun',
    mean: 'istila etmek, aşmak',
  },
  {
    v1: 'oversee',
    v2: 'oversaw',
    v3: 'overseen',
    mean: 'göz kulak olmak',
  },
  {
    v1: 'oversleep',
    v2: 'overslept',
    v3: 'overslept',
    mean: 'uyuya kalmak',
  },
  {
    v1: 'overtake',
    v2: 'overtook',
    v3: 'overtaken',
    mean: 'yetişip geçmek, sollamak',
  },
  {
    v1: 'spit',
    v2: 'spit',
    v3: 'spit',
    mean: 'tükürmek',
  },
  {
    v1: 'split',
    v2: 'split',
    v3: 'split',
    mean: 'yarmak, bölmek',
  },
  {
    v1: 'spoil',
    v2: 'spoilt',
    v3: 'spoilt',
    mean: 'berbat etmek, mahvetmek',
  },
  {
    v1: 'spread',
    v2: 'spread',
    v3: 'spread',
    mean: 'yaymak, yayılmak',
  },
  {
    v1: 'spring',
    v2: 'sprang',
    v3: 'sprung',
    mean: 'ortaya çıkıvermek, yerden bitmek',
  },
  {
    v1: 'stand',
    v2: 'stood',
    v3: 'stood',
    mean: 'ayakta durmak',
  },
  {
    v1: 'steal',
    v2: 'stole',
    v3: 'stolen',
    mean: 'çalmak',
  },
  {
    v1: 'stick',
    v2: 'stuck',
    v3: 'stuck',
    mean: 'saplamak, saplanmak',
  },
  {
    v1: 'sting',
    v2: 'stung',
    v3: 'stung',
    mean: 'sokmak, arı yılan vs. ısırmak, acıtmak',
  },
  {
    v1: 'stink',
    v2: 'stank',
    v3: 'stunk',
    mean: 'pis kokmak',
  },
  {
    v1: 'strike',
    v2: 'struck',
    v3: 'struck',
    mean: 'vurmak, çarpmak, grev yapmak',
  },
  {
    v1: 'strive',
    v2: 'strove',
    v3: 'striven',
    mean: 'çalışmak, çabalamak',
  },
  {
    v1: 'swear',
    v2: 'swore',
    v3: 'sworn',
    mean: 'küfretmek, yemin etmek',
  },
  {
    v1: 'sweep',
    v2: 'swept',
    v3: 'swept',
    mean: 'süpürmek',
  },
  {
    v1: 'swell',
    v2: 'swelled',
    v3: 'swollen',
    mean: 'şişmek, kabartmak',
  },
  {
    v1: 'swim',
    v2: 'swam',
    v3: 'swum',
    mean: 'yüzmek',
  },
  {
    v1: 'swing',
    v2: 'swung',
    v3: 'swung',
    mean: 'sallamak, sallanmak',
  },
  {
    v1: 'take',
    v2: 'took',
    v3: 'taken',
    mean: 'almak, götürmek',
  },
  {
    v1: 'teach',
    v2: 'taught',
    v3: 'taught',
    mean: 'öğretmek',
  },
  {
    v1: 'tear',
    v2: 'tore',
    v3: 'torn',
    mean: 'yırtmak',
  },
  {
    v1: 'tell',
    v2: 'told',
    v3: 'told',
    mean: 'söylemek, anlatmak',
  },
  {
    v1: 'think',
    v2: 'thought',
    v3: 'thought',
    mean: 'düşünmek',
  },
  {
    v1: 'thrive',
    v2: 'throve',
    v3: 'thrived',
    mean: 'iyiye gitmek',
  },
  {
    v1: 'throw',
    v2: 'threw',
    v3: 'thrown',
    mean: 'atmak, fırlatmak',
  },
  {
    v1: 'unbind',
    v2: 'unbound',
    v3: 'unbound',
    mean: 'çözmek, açmak, salmak',
  },
  {
    v1: 'understand',
    v2: 'understood',
    v3: 'understood',
    mean: 'meanak',
  },
  {
    v1: 'undertake',
    v2: 'undertook',
    v3: 'undertaken',
    mean: 'üzerine almak,üstlenmek',
  },
  {
    v1: 'undo',
    v2: 'undid',
    v3: 'undone',
    mean: 'çözmek, yok etmek',
  },
  {
    v1: 'uphold',
    v2: 'upheld',
    v3: 'upheld',
    mean: 'desteklemek',
  },
  {
    v1: 'wake',
    v2: 'woke',
    v3: 'woken',
    mean: 'uyanmak, uyandırmak',
  },
  {
    v1: 'wear',
    v2: 'wore',
    v3: 'worn',
    mean: 'giymek, takmak',
  },
  {
    v1: 'weave',
    v2: 'wove',
    v3: 'woven',
    mean: 'dokumak, örmek',
  },
  {
    v1: 'weep',
    v2: 'wept',
    v3: 'wept',
    mean: 'gözyaşı dökmek',
  },
  {
    v1: 'wet',
    v2: 'wet',
    v3: 'wet',
    mean: 'ıslatmak, işemek',
  },
  {
    v1: 'wind',
    v2: 'wound',
    v3: 'wound',
    mean: 'sarmak, dolamak',
  },
  {
    v1: 'win',
    v2: 'won',
    v3: 'won',
    mean: 'kazanmak',
  },
  {
    v1: 'withdraw',
    v2: 'withdrew',
    v3: 'withdrawn',
    mean: 'geri çekilmek',
  },
  {
    v1: 'withstand',
    v2: 'withstood',
    v3: 'withstood',
    mean: 'karşı koymak, direnmek',
  },
  {
    v1: 'write',
    v2: 'wrote',
    v3: 'written',
    mean: 'yazmak',
  },
];
